description = "Utility for directing compilation"
name = "make"

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "version-output"
version-command = [ "make", "--version" ]
version-regexp = ".*Make ([\\d\\.]+).*"
