# Please read the TESTING file before modifying this file

# Show differences between the submitted manifest and the previous
# release of the same crate, to enable easier catching of problems

name: Diff release

on:
  pull_request:
    paths:
      - 'index/**.toml'

env:
  CHECKS_REPO: .

jobs:

  diff:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up stable `alr`
      if: contains(github.base_ref, 'stable-')
      uses: alire-project/setup-alire@v2
      with:
        toolchain: --disable-assistant # We don't need the compiler

    - name: Set up devel `alr`
      if: contains(github.base_ref, 'devel-')
      uses: alire-project/setup-alire@v2
      with:
        toolchain: --disable-assistant # We don't need the compiler
        branch: master

    - name: DIFF releases
      run: ${{env.CHECKS_REPO}}/scripts/diff-release.sh || true # No deal breaker if failed
      shell: bash
      env:
        ALL_CRATES: TRUE
